import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { learnProject } from "./project.js";

export async function renderContextDocument(vault, input) {
  const projectRoot = resolve(input.projectRoot);
  const profile = await vault.getProjectProfile(projectRoot) || await learnProject(projectRoot);
  const memories = await vault.listMemories({ projectRoot, includeGlobal: true });
  const globalMemories = memories.filter((entry) => entry.scope === "global");
  const projectMemories = memories.filter((entry) => entry.scope === "project");
  const lines = [];

  lines.push("# Agent Context");
  lines.push("");
  lines.push("This file is generated by Across Context. It contains sanitized operating context for coding agents.");
  lines.push("");
  lines.push("## Project");
  lines.push("");
  lines.push(`- Name: ${profile.name}`);
  if (profile.summary) lines.push(`- Summary: ${profile.summary}`);
  if (profile.languages?.length) lines.push(`- Languages: ${profile.languages.join(", ")}`);
  if (profile.packageManager) lines.push(`- Package manager: ${profile.packageManager}`);
  lines.push("");

  if (Object.keys(profile.commands || {}).length) {
    lines.push("## Commands");
    lines.push("");
    for (const [name, command] of Object.entries(profile.commands)) {
      lines.push(`- ${name}: \`${command}\``);
    }
    lines.push("");
  }

  appendMemorySection(lines, "Global Preferences", globalMemories);
  appendMemorySection(lines, "Project Memory", projectMemories);

  lines.push("## Across Context Automation");
  lines.push("");
  lines.push("- Task start memory lookup: before planning or editing, search Across Context for relevant global and project memory.");
  lines.push("- During work: use project context before architecture, release, dependency, test, or documentation decisions.");
  lines.push("- Before final response memory write: remember only durable user preferences, project decisions, reusable commands, and compact session summaries.");
  lines.push("- Never write secrets, API keys, tokens, credentials, cookies, huge logs, full chat history, temporary errors, private screenshots, or one-off noise.");
  lines.push("- Prefer updating or reusing an existing memory instead of creating duplicate memories.");
  lines.push("");

  lines.push("## Safety");
  lines.push("");
  lines.push("- Do not expose API keys, tokens, private local paths, or private project names in public output.");
  lines.push("- Confirm before broad rewrites, dependency changes, destructive file operations, or release actions.");
  lines.push("- Prefer small, reviewable changes with tests or explicit verification evidence.");
  lines.push("");

  return `${lines.join("\n").trim()}\n`;
}

export async function exportContext(vault, input) {
  const projectRoot = resolve(input.projectRoot);
  const target = input.target || "agents";
  const content = await renderContextDocument(vault, { projectRoot, target });
  const path = exportPath(projectRoot, target);
  await mkdir(dirname(path), { recursive: true });
  const finalContent = target === "cursor" ? cursorRule(content) : content;
  await writeFile(path, finalContent, "utf8");
  return { path, target, bytes: Buffer.byteLength(finalContent) };
}

export function exportPath(projectRoot, target) {
  const root = resolve(projectRoot);
  if (target === "claude") return join(root, "CLAUDE.md");
  if (target === "cursor") return join(root, ".cursor", "rules", "across-context.mdc");
  if (target === "markdown") return join(root, "docs", "agent-context.md");
  return join(root, "AGENTS.md");
}

function appendMemorySection(lines, title, memories) {
  if (!memories.length) return;
  lines.push(`## ${title}`);
  lines.push("");
  for (const entry of memories) {
    const tags = entry.tags?.length ? ` [${entry.tags.join(", ")}]` : "";
    lines.push(`- (${entry.type}) ${entry.text}${tags}`);
  }
  lines.push("");
}

function cursorRule(content) {
  return `---\nalwaysApply: true\n---\n\n${content}`;
}
